### PR TITLE
v0.8.2 patch

### PR DESCRIPTION
**Pull request by yinweisu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yinweisu** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
It seems protobuf causes the issue. 

```bash
conda create -n ag python=3.10 -y
conda activate ag
conda install -c conda-forge mamba
mamba env update -n ag -f environment.yml
conda remove -n ag --all -y
```

```text
name: ag
channels:
    - conda-forge
dependencies:
    - python >=3.8,<3.11
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - pillow >=9.3,<9.6
    - tqdm >=4.38,<5
    - boto3 >=1.10,<2
    - requests >=2.21,<3
    - jsonschema >=4.14,<4.18
    - seqeval >=1.2.2,<1.3.0
    - evaluate >=0.2.2,<0.4.0
    - accelerate >=0.9,<0.17
    - timm >=0.9.2,<0.10.0
    - pytorch >=2.0,<2.1
    - torchvision >=0.15.0,<0.16.0
    - scikit-image >=0.19.1,<0.20.0
    - pytorch-lightning >=2.0.0,<2.1
    - text-unidecode >=1.3,<1.4
    - torchmetrics >=1.0.0,<1.1.0
    - transformers >=4.23.0,<4.27.0
    - nptyping >=1.4.4,<2.5.0
    - omegaconf >=2.1.1,<2.3.0
    - sentencepiece >=0.1.95,<0.2.0
    # Added because conda forge doesn't have transformers[sentencepiece].
    # Therefore, transformers doens't pin protobuf. We manually pin it
    # https://github.com/huggingface/transformers/blob/v4.27-release/setup.py#L142
    - protobuf >=3.15.3,<=3.20.2
    - pytorch-metric-learning >=1.3.0,<2.0
    - nlpaug >=1.1.10,<1.2.0
    - nltk >=3.4.5,<4.0.0
    - openmim >=0.3.7,<0.4.0
    - defusedxml >=0.7.1,<0.7.2
    - jinja2 >=3.0.3,<3.2
    - tensorboard >=2.9,<3
    - pytesseract >=0.3.9,<0.3.11
```

image

**Comment by giswqs** [comment]
There is a GitHub outage right now. The CI is not triggered. Will try later. 
https://www.githubstatus.com/

**Comment by giswqs** [comment]
@yinweisu I believe `protobuf` is the root cause. Commenting it out should resolve the issue. Is protobuf used in the default autogluon imports? If not, users can install it separately after autogluon is installed.

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
The CI has passed without protobuf. Merging it for now so that the autogluon main package can be updated. Will working on protobuf later.

**Pull request merged**
